# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.URLField(blank=True, verbose_name='domain'),
        ),
    ]
