# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='phone'),
        ),
    ]
