# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='date end')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
            ],
        ),
        migrations.CreateModel(
            name='LogCompanyMentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(to='companies.Company')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Log')),
            ],
        ),
        migrations.CreateModel(
            name='LogKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='LogPersonMentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Log')),
                ('person', models.ManyToManyField(to='people.Person')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.LogKind'),
        ),
    ]
