# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date end'),
        ),
    ]
