# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20161027_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='reminder',
            field=models.BooleanField(default=False, verbose_name='reminder'),
        ),
    ]
