# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20161027_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcompanymentions',
            name='company',
            field=models.ManyToManyField(to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='logcompanymentions',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='logs.Log'),
        ),
        migrations.AlterField(
            model_name='logpersonmentions',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='logs.Log'),
        ),
        migrations.AlterField(
            model_name='logpersonmentions',
            name='person',
            field=models.ManyToManyField(to='people.Person'),
        ),
    ]
