# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20161027_1136'),
        ('companies', '0003_auto_20161027_1136'),
        ('logs', '0006_auto_20161027_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(to='companies.Company')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='logs.Log')),
                ('person', models.ManyToManyField(to='people.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='logcompanymentions',
            name='company',
        ),
        migrations.RemoveField(
            model_name='logcompanymentions',
            name='log',
        ),
        migrations.RemoveField(
            model_name='logpersonmentions',
            name='log',
        ),
        migrations.RemoveField(
            model_name='logpersonmentions',
            name='person',
        ),
        migrations.DeleteModel(
            name='LogCompanyMentions',
        ),
        migrations.DeleteModel(
            name='LogPersonMentions',
        ),
    ]
