# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20161027_1136'),
        ('companies', '0003_auto_20161027_1136'),
        ('logs', '0007_auto_20161027_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmentions',
            name='company',
        ),
        migrations.RemoveField(
            model_name='logmentions',
            name='log',
        ),
        migrations.RemoveField(
            model_name='logmentions',
            name='person',
        ),
        migrations.AddField(
            model_name='log',
            name='companies',
            field=models.ManyToManyField(related_name='companies', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='log',
            name='people',
            field=models.ManyToManyField(related_name='people', to='people.Person'),
        ),
        migrations.DeleteModel(
            name='LogMentions',
        ),
    ]
