# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_auto_20161027_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='companies', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='log',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to='people.Person'),
        ),
    ]
