# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_auto_20161027_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='logkind',
            name='glyphicon_name',
            field=models.CharField(blank=True, default='comment', max_length=32, verbose_name='icon'),
        ),
    ]
