# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_auto_20161108_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='body_html',
            field=models.TextField(default=None, null=True),
            preserve_default=False,
        ),
    ]
