# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_log_body_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='body_html',
            field=models.TextField(null=True),
        ),
    ]
