# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_auto_20161110_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='body_html',
        ),
    ]
