# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_remove_log_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
    ]
