# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0017_log_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='public_view',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='public views'),
        ),
    ]
